export const KSB_DEFINITIONS: Record<string, string> = {
  K1: 'The broad range of creative processes involved in creative design, and the importance of being aware of all the principal design disciplines including the different perspectives, approaches or schools of thought and theories that underpin them.',
  K2: 'The broad range of industry standard creative digital design tools and methods, their strengths and weaknesses and how to apply them.',
  K3: 'How to produce and maintain a portfolio of creative digital work.',
  K4: 'The audio, visual and verbal conventions through which sounds, images and words take meaning when creating design concepts for online and non-screen based services and installations.',
  K5: 'Contemporary audio, video and film technologies, including motion graphics and voice control systems and how to apply them as part of the digital media authoring process.',
  K6: 'How to present compelling pitches and presentations of creative digital design proposals.',
  K7: 'How to interpret and work to a design brief to deliver creative digital design solutions.',
  K8: 'How to critically analyse, interpret and evaluate complex information and concepts for creative digital design to deliver compelling creative digital designs that achieve a determined business outcome.',
  K9: 'The fundamental concepts of digital design/user interface design using front end frameworks and contemporary digital technologies for different digital media platforms.',
  K10: 'How to design responsive user centred solutions, including the technical opportunities and restrictions afforded by different platforms, the impact of design on performance and interaction design across a range of media platforms.',
  K11: 'The fundamentals of user experience and user research, including user personas: needs, wants, pains, prior experiences, user-centric design, customer journeys, calls to action, information architecture and navigation, site flow and information foraging: using wireframes to prototype user journeys.',
  K12: "The fundamentals of different digital platform applications including the principles of mobile first design; including when it is, and isn't, relevant, and for multiple responsive breakpoints.",
  K13: 'The legal, ethical, regulatory, accessibility and governance frameworks which affect the development of creative design artefacts and applications and how to apply them.',
  K14: 'Contemporary methodologies such as agile and open innovation and how to apply them.',
  K15: 'The definition and fundamentals of branding; brand strength and positivity, the attributes of effective brands (excellent, different, compelling, authentic), being aware of brand meanings and values, effective brand positioning, visual tone, messaging, editorial voice and brand articulation.',
  K16: 'How to keep up to date with emerging platforms, environments and technologies.',
  K17: 'How to work with data and apply the creative digital approaches to represent complex data.',
  K18: 'The key features of the main UK laws, including Data Protection Act and General Data Protection Regulation (GDPR) and the opportunities and constraints offered by data and what is feasible / needed for the current project / task.',
  K19: 'How to undertake real world 3D digital capture and process 3D data.',
  K20: 'The principles, controls and workflow inherent in building, texturing, animating and rendering 3D models, including XYZ Space, scaling and transforms, and the range of uses in the real world (e.g. Architecture, Construction, Games, Immersive, Automotive, Aerospace, Medical, Space etc.).',
  K21: 'The fundamentals, origins, application and potential of contemporary immersive technologies, such as AR (Augmented Reality), VR (Virtual Reality) and XR (Mixed Reality), including psychology aspects of 3D environments, and the uses in the real world (including Internet of Things, Architecture, Construction, Games, Retail, Automotive, Aerospace, Medical etc.).',

  S1: 'Apply creative design processes to all creative digital development projects, including online services and installations and non-screen-based media, producing designs compelling to customers / users and to leverage the multitude of digital touch points including, but not limited to; mobile, tablet, laptop, desktop, wearable, consoles and cars.',
  S2: 'Create designs using industry standard methods; Typography, Digital Art, Video and Special Effects, Rendering, Animation, 3D Graphics and Digital Photography.',
  S3: 'Create eye-catching creative design concepts and prototypes for presentation to clients using industry standard tools and advanced methods to address design problems set by clients.',
  S4: "Create 'production' ready digital media assets including, but not limited to designs, style guides, animations, videos, story boards, images, audio to achieve a determined business outcome.",
  S5: 'Select, refine, adapt and apply industry standard contemporary creative digital design technologies, and working with data to develop creative design solutions. Apply and leverage data e.g. personalisation, behavioural, location, weather, in design concepts and solutions.',
  S6: 'Communicate design concepts and solutions to team members, designers, brand managers, product leads, marketing directors, commercial and sales in a strong and compelling manner, evaluating the outputs and methods used and their implications.',
  S7: 'Use design concept digital art to deliver creative design sales pitches to clients.',
  S8: 'Brief and work with third parties such as photographers, model makers, agencies and data professionals.',
  S9: 'Produce and maintain a portfolio of creative digital work.',
  S10: "Keep abreast of industry developments, creative trends and innovations, knowing what's emerging, and when and when to act to make cost effective use of new and emerging tools and technologies.",
  S11: 'Input into market/user research and UX briefs and work with their outputs.',
  S12: 'Collaborate between team members, clients and working with a range of stakeholders including market researchers, user experience professionals, user researchers, developers, photographers, model makers, brand managers, product leads, marketing directors, commercial, sales and communication specialists.',
  S13: 'Review and build accessibility requirements into all interactive creative digital media solutions.',
  S14: 'Work effectively both individually and collaboratively as part of a multidisciplinary team, with methodologies such as agile, building and maintaining positive relationships with team members, clients and other stakeholders.',
  S15: 'Lead and manage end to end creative digital design projects in line with governance policies, meeting deadlines and managing client expectations for different environments, including agile.',
  S16: 'Deliver well-designed, high quality creative digital solutions including prototyping skills within organisational brand guidelines.',
  S17: 'Design interactive artefacts using industry standard immersive technology techniques.',
  S18: 'Be able to plan and undertake own development and life-long learning to keep abreast of emerging technologies and techniques to review how these are best.',

  B1: 'A passion for creating content for creative and digital media.',
  B2: 'A strong work ethic and commitment to meet the standards required.',
  B3: 'Support for others in developing an appropriate balance of leadership and technical skills.',
  B4: 'Recognition and compliance with equality and diversity in the workplace.',
  B5: 'Demonstrates resilience, accountability and flexibility especially when managing difficult situations.',
};

export const getKSBDescription = (code: string): string => {
  return KSB_DEFINITIONS[code] || 'Definition unavailable for this code.';
};